Use flexbox for table header
plotly/dash pull request #1776
Opened 2021-09-23 17:55 UTC by tmpacifitech

2021-09-23 17:56 UTC, tmpacifitech commented on components/dash-table/src/dash-table/components/Table/Table.less
>                  }
This is the only changes on this less file.. other changes are just prettier fix.

2021-09-23 17:58 UTC, tmpacifitech commented
Another fix for https://github.com/plotly/dash-table/issues/867

2021-09-24 06:16 UTC, akksi requested changes
- Looks like one of the Percy tests is failing (https://app.circleci.com/pipelines/github/plotly/dash/2707/workflows/6936fe57-0c84-4d9f-b4b7-c47452fe9a6e/jobs/44310)
- If there are multiple buttons/icons in a column, they should be wrapped in a container so all of them would be aligned left OR, maybe it would work to always add `margin-left: auto` to the text, so it will put the spacing between the icons and the text (I like the second solution better).
- Do we need to keep the `float: left` properties?

2022-04-22 20:07 UTC, alexcjohnson commented
Looks like we had multiple parallel fixes for this... 🙈

2022-04-22 20:07 UTC, closed without merging