Update dash.py
plotly/dash pull request #1993
Opened 2022-03-28 19:24 UTC by deepyaman

*Start with a description of this PR. Then edit the list below to the items that make sense for your PR scope, and check off the boxes as you go!*

## Contributor Checklist

- [ ] I have broken down my PR scope into the following TODO tasks
   -  [ ] task 1
   -  [ ] task 2
- [ ] I have run the tests locally and they passed. (refer to testing section in [contributing](https://github.com/plotly/dash/blob/master/CONTRIBUTING.md))
- [ ] I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR

### optionals

- [ ] I have added entry in the `CHANGELOG.md`
- [ ] If this PR needs a follow-up in **dash docs**, **community thread**, I have mentioned the relevant URLS as follows
    -  [ ] this GitHub [#PR number]() updates the dash docs
    -  [ ] here is the show and tell thread in Plotly Dash community

2022-03-28 19:34 UTC, deepyaman commented
Closing this PR, as upgrading to Werkzeug 2.1.0 would mean dropping support for Python 3.6, which is a much bigger decision.

2022-03-28 20:02 UTC, deepyaman commented on requires-install.txt
> +Werkzeug<2.1.0  # Werkzeug 2.1.0 dropped support for Python 3.6
```suggestion
Werkzeug<2.1.0  # Werkzeug 2.1.0 dropped support for Python 3.6
click<8.1.0  # click 8.1.0 dropped support for Python 3.6
```

2022-03-28 20:03 UTC, deepyaman commented on requires-all.txt
> +Werkzeug<2.1.0  # Werkzeug 2.1.0 dropped support for Python 3.6
```suggestion
Werkzeug<2.1.0  # Werkzeug 2.1.0 dropped support for Python 3.6
click<8.1.0  # click 8.1.0 dropped support for Python 3.6
```

2022-03-28 20:03 UTC, deepyaman commented on CHANGELOG.md
> +- [#1993](https://github.com/plotly/dash/pull/1993) Pin Flask<2.1.0 and Werkzeug<2.1.0 to retain Python 3.6 compatibility, resolving [#1992](https://github.com/plotly/dash/issues/1992).
```suggestion
- [#1993](https://github.com/plotly/dash/pull/1993) Pin Flask<2.1.0, Werkzeug<2.1.0, and click<8.1.0 to retain Python 3.6 compatibility, resolving [#1992](https://github.com/plotly/dash/issues/1992).
```

2022-03-29 11:22 UTC, flying-sheep requested changes
Version upper bounds are no good approach for library projects: https://iscinumpy.dev/post/bound-version-constraints/

You should instead write conditional code handling all flask/werkzeug versions or (if that’s too hard) drop Python 3.6 support

2022-03-29 11:33 UTC, deepyaman commented
> Version upper bounds are no good approach for library projects: https://iscinumpy.dev/post/bound-version-constraints/
> 
> You should instead write conditional code handling all flask/werkzeug versions or (if that’s too hard) drop Python 3.6 support

@flying-sheep I can do either. I don't see much examples of conditional Python version handling within Dash (only https://github.com/plotly/dash/blob/3334c07f59cb1ee9bc4596ebbdce6edb41f94968/dash/development/component_generator.py#L154 outside of tests, but even that's for a component generator), but I've seen plenty of it in other libraries. I would personally also be fine to drop 3.6, but don't think that's my call.

Are you one of the maintainers of Dash? Just want to makes sure the change is aligned with whoever will be making the final call.

2022-03-29 11:48 UTC, flying-sheep commented
I’m not, sorry if I gave the impression. I think you can see that by the color of my review icon: mine is gray, so it’s just a “suggested change” and not a “requested change”.

I’m just speaking from my history of dealing with compatibility problems and bugs in python libraries. That blog post I linked really nails it IMHO, and I think any library maintainer should read it.

2022-03-29 14:54 UTC, alexcjohnson commented
Py3.6 still accounts for about [10% of our downloads](https://pypistats.org/packages/dash) so I don't think it's time to drop it yet. 3.7 is still the most used though it's about to lose that title to 3.8 finally.

2022-03-29 19:47 UTC, deepyaman commented on requires-all.txt
> +black==22.3.0
```suggestion
black==21.6b0;python_version<"3.7"
black==22.3.0;python_version>="3.7"
```

2022-03-29 19:48 UTC, deepyaman commented on requires-ci.txt
> +black==22.3.0
```suggestion
black==21.6b0;python_version<"3.7"
black==22.3.0;python_version>="3.7"
```

2022-03-29 21:00 UTC, alexcjohnson commented
Thanks @deepyaman - we ended up going with #1995 so I'll close this one but your work here was helpful toward fully understanding the issue!

2022-03-29 21:00 UTC, closed without merging